baseurl: https://tempered.works
languageCode: en-gb
theme: beautifulhugo
title: Tempered Works Ltd.
pygmentsCodeFences: true
pygmentsUseClasses: true
#enableGitInfo: true
enableEmoji: true


params:
  hometitle: Tempered Works
  subtitle: Software and Data Consulting Services
  logo: /favicons/android-chrome-192x192.png
  profilePicture: /favicons/android-chrome-512x512.png
  favicon: /favicons/favicon.ico
  mainSections: [post, posts]
  rss: true
  comments: true
  readingTime: true
  wordCount: false
  selfHosted: false
  socialShare: true
  showRelatedPosts: true

author:
  name: Paul Brabban
  email: paul@tempered.works
  github: brabster
  linkedin: paulbrabban
  twitter: brabter


menu:
  main:
    - name: Portfolio
      weight: 200
      url: /portfolio/
    - name: Blog
      weight: 300
      url: /posts/
    - name: Tags
      weight: 400
      url: /tags/
    - name: Company
      weight: 500
      url: /company/

markup:
  goldmark:
    renderer:
      unsafe: true
  
server:
  headers:
  - for: /**
    values:
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"
      X-Content-Type-Options: "nosniff"
      Referrer-Policy: "no-referrer-when-downgrade"
      Content-Security-Policy: "default-src 'unsafe-inline' 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://maxcdn.bootstrapcdn.com https://use.fontawesome.com https://code.jquery.com"