languageCode = "en-gb"
theme = "anatole"

[params]
title = "Tempered Works"
author = "Paul Brabban"
description = "Software and Data Consulting Services"
profilePicture = "/about/profile.jpeg"
displayMode = "dark"
images = "/about/profile.jpeg"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/paulbrabban"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/brabster"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "instagram"
url = "https://twitter.com/brabster"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:paul@tempered.works"