languageCode = "en-gb"
theme = "anatole"

[params]
title = "Tempered Works"
author = "Tempered Works"
description = "Software and Data Consulting Services"
profilePicture = "/favicons/android-chrome-512x512.png"
favicon = "/favicons/"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Posts"
  weight = 300
  identifier = "posts"
  url = "/posts/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/paulbrabban"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/brabster"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "instagram"
url = "https://twitter.com/brabster"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:paul@tempered.works"

[markup.goldmark.renderer]
unsafe = true